### ISSUE TITLE
Compilation issue with rPi 4

### ISSUE THREAD

**Issue by abinash** [RealTimeLogic/BAS#3]
I am getting following comilation error for https://raw.githubusercontent.com/RealTimeLogic/BAS/main/LinuxBuild.sh
--2022-07-07 13:31:09--  https://raw.githubusercontent.com/RealTimeLogic/BAS/main/LinuxBuild.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2384 (2.3K) [text/plain]
Saving to: ‘STDOUT’
                                              100%[=========================================================================================================================================>]   2.33K  --.-KB/s    in 0.003s  

2022-07-07 13:31:09 (866 KB/s) - written to stdout [2384/2384]

Setting default compiler
Using compiler gcc
Compiling using gcc; this may take some time........
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
as: error while loading shared libraries: /lib/aarch64-linux-gnu/libopcodes-2.35.2-system.so: unsupported version 0 of Verneed record
71

I am using following version
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by surfskidude** [comment]
I am closing this issue since the following works on my RPI:
wget -O - https://raw.githubusercontent.com/RealTimeLogic/BAS/main/LinuxBuild.sh | bash

**Comment by paulwratt** [comment]
As long as you realise he's using aarch64 Debian Bullseye, not RPiOS Bullseye

**Comment by surfskidude** [comment]
> As long as you realise he's using aarch64 Debian Bullseye, not RPiOS Bullseye

In any event, the error is related to the toolchain and not compiling the code.
