### ISSUE TITLE
[Feature Request] to close the response output stream early: "response:eof()"

### ISSUE THREAD

**Issue by diyism** [RealTimeLogic/BAS#4]
In nginx-lua/openresty, I can close the http response early (avoid my users waiting) and continue doing things that cost time on my server:

```
ngx.say("bye bye, my user")
ngx.eof()
local http=require"httpc".create()
http:request{method="GET", url="https://a web page of very long content"}
local data,err=http:read"*a"
```

Does the Mako web server have such an API? for example: response:eof()

**Comment by diyism** [comment]
Although There's another async task calling method:

```
local function q()
        local http=require"httpc".create()
        http:request{method="GET",
                     url="https://a web page of very long content"
                    }
        local data,err=http:read"*a"
        os.execute("/usr/bin/sudo /home/malcolm/lcus1.sh")
end
ba.timer(q):set(0)
```

**Comment by surfskidude** [comment]
In mako, you would do the following to end the response (you defer the execution of the http client):
ba.thread.run(function()
  local http=require"httpc".create()
  http:request{method="GET", url="https://a web page of very long content"}
  local data,err=http:read"*a" end)
